--
-- 2021-12-10
--
ALTER TABLE `entities` CHANGE `is_player` `is_player` TINYINT(1) UNSIGNED NOT NULL, ADD `ignore` TINYINT(1) UNSIGNED NULL DEFAULT NULL , ADD `cmd` TINYINT(1) UNSIGNED NULL DEFAULT NULL ;

ALTER TABLE `events` CHANGE `victim_id` `victim_id` INT(10) UNSIGNED NULL DEFAULT NULL, CHANGE `weapon` `weapon` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL, ADD `data` VARCHAR(255) NULL DEFAULT NULL ;

UPDATE `events` SET `weapon`=NULL WHERE `event` NOT IN ('hit', 'killed') ;

ALTER TABLE `operations` ADD `verified` TINYINT(1) UNSIGNED NULL DEFAULT NULL ;

ALTER TABLE `players` ADD `uid` VARCHAR(64) NULL DEFAULT NULL , ADD `unit_id` VARCHAR(64) NULL DEFAULT NULL , ADD UNIQUE (`uid`) ;

